
export const BOOK_TICKET_REQUEST = "BOOK_TICKET_REQUEST"
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS"
export const BOOK_TICKET_FAIL = "BOOK_TICKET_FAIL"

export const GET_ROOM_TICKETLIST_REQUEST = "GET_ROOM_TICKETLIST_REQUEST"
export const GET_ROOM_TICKETLIST_SUCCESS = "GET_ROOM_TICKETLIST_SUCCESS"
export const GET_ROOM_TICKETLIST_FAIL = "GET_ROOM_TICKETLIST_FAIL"
