
// get list seat
export const GET_LISTSEAT_REQUEST = "GET_LISTSEAT_REQUEST"
export const GET_LISTSEAT_SUCCESS = "GET_LISTSEAT_SUCCESS"
export const GET_LISTSEAT_FAIL = "GET_LISTSEAT_FAIL"

// selecting seat
export const ADD_DATA_MALICHCHIEU_TAIKHOANNGUOIDUNG = "ADD_DATA_MALICHCHIEU_TAIKHOANNGUOIDUNG"
export const CHANGE_LISTSEAT = "CHANGE_LISTSEAT"
export const INIT_DATA_REBOOKING = "INIT_DATA_REBOOKING"
export const SET_PAYMENT_METHOD = "SET_PAYMENT_METHOD"

// booking ticked
export const BOOK_TICKET_REQUEST = "BOOK_TICKET_REQUEST"
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS"
export const BOOK_TICKET_FAIL = "BOOK_TICKET_FAIL"

// control modal
export const OPEN_MODAL_BYTIMEOUT = "OPEN_MODAL_BYTIMEOUT"
