export const LOADING_LAZY_MOUNT = "LOADING_LAZY_MOUNT"
export const LOADING_LAZY_UNMOUNT = "LOADING_LAZY_UNMOUNT"
export const LOADING_BACKTO_HOME = "LOADING_BACKTO_HOME"
export const LOADING_BACKTO_HOME_COMPLETED = "LOADING_BACKTO_HOME_COMPLETED"