
export const GET_MOVIE_SHOWTIMES_REQUESS = 'GET_MOVIE_SHOWTIMES_REQUEST' // LayThongTinLichChieuPhim
export const GET_MOVIE_SHOWTIMES_SUCCESS = 'GET_MOVIE_SHOWTIMES_SUCCESS'
export const GET_MOVIE_SHOWTIMES_FAIL = 'GET_MOVIE_SHOWTIMES_FAIL'
export const RESET_MOVIEDETAIL_REDUCER = 'RESET_MOVIEDETAIL_REDUCER'