
export const GET_MOVIE_SHOWTIMES_REQUESS = 'GET_MOVIE_SHOWTIMES_REQUEST' // LayThongTinLichChieuPhim
export const GET_MOVIE_SHOWTIMES_SUCCESS = 'GET_MOVIE_SHOWTIMES_SUCCESS'
export const GET_MOVIE_SHOWTIMES_FAIL = 'GET_MOVIE_SHOWTIMES_FAIL'
export const RESET_MOVIEDETAIL_REDUCER = 'RESET_MOVIEDETAIL_REDUCER'

export const GET_COMMENT_REQUESS = 'GET_COMMENT_REQUESS'
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS'
export const GET_COMMENT_FAIL = 'GET_COMMENT_FAIL'

export const POST_COMMENT_REQUESS = 'POST_COMMENT_REQUESS'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL'

export const LIKE_COMMENT_REQUESS = 'LIKE_COMMENT_REQUESS'
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS'
export const LIKE_COMMENT_FAIL = 'LIKE_COMMENT_FAIL'