export const GET_MOVIE_LIST_REQUEST = 'GET_MOVIE_LIST_REQUEST';
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS';
export const GET_MOVIE_LIST_FAIL = 'GET_MOVIE_LIST_FAIL';

export const GET_MOVIE_DETAIL_REQUEST = 'GET_MOVIE_LIST_REQUEST'
export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS'
export const GET_MOVIE_DETAIL_FAIL = 'GET_MOVIE_LIST_FAIL'

export const GET_MOVIE_LISTBYDAY_REQUEST = 'GET_MOVIE_LISTBYDAY_REQUEST';
export const GET_MOVIE_LISTBYDAY_SUCCESS = 'GET_MOVIE_LISTBYDAY_SUCCESS';
export const GET_MOVIE_LISTBYDAY_FAIL = 'GET_MOVIE_LISTBYDAY_FAIL';