export const GET_MOVIE_LIST_REQUEST = 'GET_MOVIE_LIST_REQUEST';
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS';
export const GET_MOVIE_LIST_FAIL = 'GET_MOVIE_LIST_FAIL';

export const GET_MOVIE_DETAIL_REQUEST = 'GET_MOVIE_LIST_REQUEST'
export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS'
export const GET_MOVIE_DETAIL_FAIL = 'GET_MOVIE_LIST_FAIL'

export const GET_ROOM_TICKET_REQUEST = 'GET_MOVIE_LIST_REQUEST'
export const GET_ROOM_TICKET_SUCCESS = 'GET_ROOM_TICKET_SUCCESS'
export const GET_ROOM_TICKET_FAIL = 'GET_MOVIE_LIST_FAIL'

export const GET_THEATERS_REQUESS = 'GET_THEATERS_REQUEST'
export const GET_THEATERS_SUCCESS = 'GET_THEATERS_SUCCESS'
export const GET_THEATERS_FAIL = 'GET_THEATERS_FAIL'