export const GET_THEATERS_SHOWTIME_REQUEST = "GET_THEATERS_SHOWTIME_REQUEST" // LayThongTinLichChieuHeThongRap
export const GET_THEATERS_SHOWTIME_SUCCESS = "GET_THEATERS_SHOWTIME_SUCCESS"
export const GET_THEATERS_SHOWTIME_FAIL = "GET_THEATERS_SHOWTIME_FAIL"

export const GET_THEATERS_SHOWTIME_REQUEST2 = "GET_THEATERS_SHOWTIME_REQUEST2"
export const GET_THEATERS_SHOWTIME_SUCCESS2 = "GET_THEATERS_SHOWTIME_SUCCESS2"
export const GET_THEATERS_SHOWTIME_FAIL2 = "GET_THEATERS_SHOWTIME_FAIL2"
