export const GET_THEATERS_SHOWTIME_REQUEST = "GET_THEATERS_SHOWTIME_REQUEST" // LayThongTinLichChieuPhim
export const GET_THEATERS_SHOWTIME_SUCCESS = "GET_THEATERS_SHOWTIME_SUCCESS"
export const GET_THEATERS_SHOWTIME_FAIL = "GET_THEATERS_SHOWTIME_FAIL"