export const GET_USER_LIST_REQUEST = 'GET_USER_LIST_REQUEST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAIL = 'GET_USER_LIST_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const RESET_USER_LIST = 'RESET_USER_LIST';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'

export const SET_IS_EXIST_USER_MODIFIED = 'SET_IS_EXIST_USER_MODIFIED'

export const GET_INFO_USER_REQUEST = 'GET_INFO_USER_REQUEST'
export const GET_INFO_USER_SUCCESS = 'GET_INFO_USER_SUCCESS'
export const GET_INFO_USER_FAIL = 'GET_INFO_USER_FAIL'